---
- name: See if pip is installed already
  command: "pip --version"
  changed_when: false
  failed_when: false
  register: pip_installed

- block:

  - name: Download pip
    get_url: url=https://bootstrap.pypa.io/get-pip.py
             dest=/tmp

  - name: Install pip
    command: "python /tmp/get-pip.py"

  - name: Remove file after install
    file: path=/tmp/get-pip.py
          state=absent

  when: pip_installed.rc != 0

- name: Ensure docker-py is installed
  pip: name=docker-py

- name: Make directory
  file: path=/home/vagrant/slave
        state=directory
        owner=vagrant

- name: Copy files
  copy: src=dind-jenkins-slave-master/{{ item }}
        dest=/home/vagrant/slave/{{ item }}
  with_items:
    - Dockerfile
    - wrapdocker
    - jenkins-slave-startup.sh

- name: Build slave image
  docker_image:
    path: /home/vagrant/slave/
    name: jenkins-slave