# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # centos 7 has networking issues w/ vagrant atm
  # http://stackoverflow.com/questions/32518591/centos7-with-private-network-lost-fixed-ip
  config.vm.box = "williamyeh/ubuntu-trusty64-docker"

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end

  config.vm.define "dockerhost" do |dockerhost|
    dockerhost.vm.network :private_network, ip: "192.168.10.10"
    dockerhost.vm.hostname = "dockerhost"
    dockerhost.vm.provision :ansible do |ansible|
      ansible.playbook = "provisioning/dockerhost/playbook.yml"
      ansible.sudo = true
    end
  end
end
